spring:
  # ===================================================================
  # Datasource
  # ===================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/BackendService
    username: BackendService
    name:
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true


