version: '3.5'
services:
  backend-service-postgresql:
    container_name: backend-service-postgresql
    image: postgres:16.6-alpine
    environment:
      - POSTGRES_USER=BackendService
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    networks:
      - backendservice
networks:
  backendservice:
    name: backendservice
    driver: bridge